---
#- name: Mettre à jour la liste des paquets
#  apt:
#    update: yes

#- name: Mettre à jour les paquets
#  apt:
#    upgrade: yes

- name: Installer le pack Apache / PHP
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-ssh2
    state: present

- name: Installer git
  apt:
    name: git
    state: present

- name: Demarre Apache en cas de redémarrage
  lineinfile:
    path: /root/start.sh
    line: "service apache2 start"
    insertafter: EOF