---
# Variable en entrée :
# FQDN
- name: Trouver le container à partir du FQDN
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Retrouver le nom du conteneur à partir du label
      command: docker ps --filter "label=FQDN={{FQDN}}"  --format "{{ '{{' }}.Names{{ '}}' }}"
      register: container_name_output
      changed_when: false

    - name: Extrait le nom du container à partir du résultat brute.
      set_fact:
        container_name: "{{ container_name_output.stdout_lines[0] }}"
      when: container_name_output.stdout_lines[0] is defined

    - name: Site-web introuvable
      fail:
        msg: "Le site-web {{ FQDN }} est rattaché à aucun conteneur !"
      when: container_name_output.stdout_lines[0] is not defined

    - debug:
        msg: "Le nom du conteneur est {{ container_name  }}"

- name: Suppression de l'ensemble
  hosts: localhost
  become: yes
  gather_facts: no
  #vars:
  #  - container_name: "{{ hostvars['localhost']['container_name'] }}"
  tasks:
  #  - Name: Arrête le container {{ container_name }}
  #    docker_container:
  #      name: "{{ container_name }}"
  #      state: stopped
    - name: Supprime le container {{ container_name }}
      docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Supprime le dossier SSH et web
      file:
        path: "{{item}}"
        state: absent
        owner: root
        group: root
      loop:
        - ../ressources/keys/{{container_name}}/
        - ../ressources/web/{{container_name}}/

- name: Supprime l'ensemble sur proxyinverse1
  hosts: proxyinverse1
  become: yes
  gather_facts: no
  tasks:
    - name: Désactive la conf {{ FQDN }}.conf
      command: a2dissite {{ FQDN }}.conf
    
    - name: supprime la conf {{ FQDN }}.conf
      file:
        path: "/etc/apache2/sites-available/{{FQDN}}.conf"
        state: absent
        owner: root
        group: root