---
- name: Activer les modules pour le ProxyInverse
  hosts: proxyinverse1
  become: yes
  tasks:
    - name: Active le module mod_proxy
      command: a2enmod proxy
    - name: Active le mode proxy_http
      command: a2enmod proxy_http

- name: Mise en place du ProxyInverse pour PhpMyAdmin
  hosts: proxyinverse1
  vars:
    - FQDN: "phpmyadmin.ansible.local"
    - Name: "PHPMYADMIN"
    - Ipv4Port: "80"
    - Ipv4Dest: "{{ hostvars['phpmyadmin']['ansible_host'] }}"
    - template: "ReverseProxyWebsite_no-ACL.j2"
  roles:
    - template_proxyinverse

- name: Interdire les accès http depuis une adresse IP en entrée
  hosts: proxyinverse1
  become: yes
  tasks:
    - name: Copier le fichier deny ip vers le proxyinverse
      copy:
        src: ../ressources/Templates/_deny_direct-ip.conf
        dest: /etc/apache2/sites-available/_deny_direct-ip.conf
    - name: Activer la conf
      command: a2ensite _deny_direct-ip.conf
    - name: Redemarrer le service Apache
      command: service apache2 restart
